<?php

// builds js and css dependencies
$this->rcmUserBuildHtmlHead();
$this->headLink()->appendStylesheet($this->url('RcmUserAdminCss'));
$this->headScript()->appendFile($this->url('RcmUserAdminUserJs'));

?>
<div ng-app="rcmuserAdminUsersApp">
    <div class="rcmuser" ng-controller="rcmuserAdminUsers">
        <div class="container-fluid admin-users">
            <div class="container-fluid">
                <h1>Users
                    <small>Edit and create users</small>
                </h1>
                <p class="lead">Set up new users or edit existing.</p>
            </div>

            <form class="search-header form-horizontal" role="userSearch">
                <div class="form-group">
                    <div class="col-sm-3">
                        <input
                            class="form-control input-sm"
                            name="userSearch"
                            ng-model="userQuery"
                            placeholder="search"
                            type="text"
                            />
                    </div>
                    <div class="col-sm-offset-7 col-sm-2">
                        <button type="button" class="btn btn-primary btn-xs" ng-click="">
                            <i class="glyphicon glyphicon-plus"></i> add user
                        </button>
                    </div>
                </div>
            </form>

            <accordion class="useraccordion" close-others="oneAtATime">

                <!-- USER -->
                <accordion-group
                    heading="{{user.id}}"
                    is-open="accordionOpen"
                    ng-repeat="user in users | userFilter:userQuery"
                    >

                    <accordion-heading>
                        <div class="accordion-heading">
                            <span class="user-username">{{user.username}}</span>
                            <span class="use-id">({{user.id}})</span>
                            <i
                                class="opener glyphicon"
                                ng-class="{'glyphicon-chevron-down': isopen, 'glyphicon-chevron-right': !isopen}"
                                >
                            </i>
                        </div>
                    </accordion-heading>

                    <accordion-heading class="accordion-body">
                        <div class="accordion-inner" ng-controller="rcmuserAdminUser" ng-init="user=user;">
                            <section class="user">
                                <div class="userDetails">
                                    <form role="form">
                                        <div class="form-group">
                                            <label for="id">Id: </label>

                                            <div id="id">
                                                {{user.id}}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="username">Username: </label>
                                            <input
                                                class="form-control"
                                                id="username"
                                                ng-model="user.username"
                                                placeholder="Username"
                                                type="text"
                                                />
                                        </div>

                                        <div class="form-group">
                                            <label for="password">Password</label>
                                            <input
                                                class="form-control"
                                                id="password"
                                                ng-model="user.password"
                                                placeholder="********"
                                                type="password"
                                                />
                                        </div>

                                        <div class="form-group">
                                            <label for="state">User state: </label>

                                            <select
                                                class="form-control"
                                                id="state"
                                                ng-model="user.state"
                                                ng-options="state as state for state in availableStates"
                                                >
                                                <option value="">n/a</option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label for="roles">Roles: </label>

                                            <div class="container-fluid user_roles">
                                                <div class="row" id="roles">

                                                    <div class="col-sm-6">
                                                        <div class="input-group" ng-repeat="role in user.properties[rolePropertyId]">
                                                            <input type="text" class="form-control" disabled="disabled" ng-value="role"/>
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-warning btn-xs" type="button">Remove</button>
                                                    </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-offset-2 col-sm-3">
                                                        <div class="btn-group" dropdown is-open="status.isopen">
                                                            <button
                                                                type="button"
                                                                class="btn btn-primary btn-xs dropdown-toggle"
                                                                data-toggle="dropdown"
                                                                ng-disabled="disabled"
                                                                >
                                                                <i class="glyphicon glyphicon-edit"></i>
                                                                + add role
                                                                <span class="caret"></span>
                                                            </button>
                                                            <ul class="dropdown-menu" role="menu">
                                                                <li ng-repeat="role in roles">
                                                                    <a href="#">{{role.roleId}}</a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="">
                                    <button type="button" class="btn btn-primary btn-xs" ng-click="saveUser()" ng-hide="">
                                        <i class="glyphicon glyphicon-edit"></i> save user
                                    </button>
                                    <button type="button" class="btn btn-warning btn-xs" ng-click="openRemoveUser()" ng-hide="">
                                        <i class="glyphicon glyphicon-minus"></i> remove user
                                    </button>
                                    <button type="button" class="btn btn-xs" ng-click="openEditUser()" ng-hide="">
                                        <i class="glyphicon glyphicon-edit"></i> edit user properties
                                    </button>
                                </div>
                            </section>

                            <section class="userProperties">
                                <div class="loading" ng-show="loading">LOADING...</div>

                                <div rcm-alerts rcm-results="alerts" alert-title="'An error occured:'"></div>

                                <div class="userEdit" ng-show="showEdit">
                                    EDIT
                                    {{user | json}}
                                </div>
                            </section>

                        </div>

                </accordion-group>

            </accordion>

        </div>
        <button type="button" class="btn btn-info btn-xs" ng-click="showMessages = !showMessages" ng-show="messages">
            <i class="glyphicon glyphicon-edit"></i>
            <span ng-hide="showMessages">show errors</span>
            <span ng-show="showMessages">hide errors</span>
        </button>
        <div class="messages" ng-show="showMessages">
            <div class="alert alert-warning">
                <ul>
                    <li ng-repeat="message in messages">{{message}}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
