<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmUser\Module'                        => __DIR__ . '/Module.php',
    'RcmUser\Controller\UserController' => __DIR__ . '/src/RcmUser/Controller/UserController.php',
    'RcmUserTest\Framework\TestCase'        => __DIR__ . '/tests/RcmUser/Framework/TestCase.php',
    'RcmUserTest\SampleTest'                => __DIR__ . '/tests/RcmUser/SampleTest.php',
);