<?php
/*
 * @todo This may be wrapped in a service so the application can determine dependencies
 *
 */
$this->rcmIncludeAngularJs(
    array(
        'js' => array(
            'angular-ui/bootstrap/ui-bootstrap-tpls-0.10.0.min.js'
        )
    )
);

$this->rcmIncludeTwitterBootstrap(
    array(
        'css' => array(
            'css/bootstrap-theme.css',
            //'css/bootstrap-theme.css.map',
        )
    )
);
/*
 * END SERVICE
 */
$css = file_get_contents(__DIR__ . '/../../css/styles.css');
$js = file_get_contents(__DIR__ . '/../../js/rcmuser.admin.acl.app.js');
$headStyle = $this->headStyle();
$headScript = $this->headScript();

$headStyle->appendStyle($css); // NOT WORKING!!!!!
$headScript->appendScript($js);



?>
<style type="text/css">

    <?= $css ?>

</style>

<div class="rcmuser" ng-app="rcmuser.admin.acl.app">
    <div class="container-fluid admin-acl">

        <div class="container-fluid">
            <h1>Access
                <small>Control user roles and access</small>
            </h1>
            <p class="lead">Set up the user roles and access to resources.</p>
        </div>

        <div class="container-fluid">

            <accordion close-others="true">

                <?php
                /* <ROLE> */
                foreach($roles as $role) {

                ?>
                <!-- + ROLE -->
                <accordion-group is-open="isopen<?= $role->getId() ?>">

                    <accordion-heading>
                        <div class="accordion-heading">
                            <a href="#" tooltip-placement="right" tooltip="This is the user role."><?= $role->getRoleIdentity() ?></a>
                            <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': isopen<?= $role->getId() ?>, 'glyphicon-chevron-right': !isopen<?= $role->getId() ?>}"></i>
                        </div>
                    </accordion-heading>

                    <!-- + RESOURCE -->
                    <?php
                    /* <RESOURCE> */
                    foreach($resources as $resource => $data) {

                    ?>
                    <div class="container-fluid admin-acl-resource-section">

                        <div class="container-fluid admin-acl-resource-row">
                            <div class="admin-acl-resource-col">
                                &#124;&#8212;<?= str_repeat("&#8212;", $data['level']) ?>&nbsp;<span><?= $resource ?></span>
                            </div>
                        </div>

                        <div class="container admin-acl-permissions-row">

                            <form class="form-inline" role="form">

                                <?php
                                /* <PRIVILEGE> */
                                foreach($rootPrivileges as $privilege) {

                                ?>
                                <div class="form-group">
                                    <label class="control-label" for="permission1"><?= $privilege ?></label>
                                    <select class="form-control input-sm" id="permission1">
                                        <option value="inherit">inherit</option>
                                        <option value="allow">allow</option>
                                        <option value="deny">deny</option>
                                    </select>
                                </div>
                                <?php
                                }
                                /* </PRIVILEGE> */
                                ?>
                            </form>

                        </div>
                    </div>
                    <!-- + RESOURCE -->
                    <?php
                    }
                    /* </RESOURCE> */
                    ?>
                </accordion-group>
                <!-- - ROLE -->
                <?php
                }
                /* </ROLE> */
                ?>

            </accordion>
        </div>
    </div>
</div>
