<?php
?>
<pre>
<?php
/* ACL STUFF
$x = $this->isAllowed('pants', 'wear');

$u = $this->zfcUserIdentity();

var_dump($u);

$acl = new Acl();
*/
//$userService = new RcmUser\Service\RcmUserService();
//var_dump($userService->getUserInputFilter()); die;

$user = $userService->buildNewUser();

//$user->setId('d1c0967c-844f-4c0f-94b1-0b9bafec970b');
$user->setUsername('Brian2');
$user->setPassword('1231231232');

echo "**Before action:\n";
var_dump($user);


/* CRUD ***********************************/
/* CREATE *
$result = $userService->createUser($user);

echo "**After create:\n";
if(!$result->isSuccess()){

    echo "ERROR: ";
    var_dump($result->getMessages());
}

var_dump($result->getUser());
/* */

/* READ *
$result = $userService->readUser($user);

echo "**After read:\n";
if(!$result->isSuccess()){

    echo "ERROR: ";
    var_dump($result->getMessages());
}

var_dump($result->getUser());
/* */

/* UPDATE *
$result = $userService->updateUser($user);

echo "**After update:\n";
if(!$result->isSuccess()){

    echo "ERROR: ";
    var_dump($result->getMessages());
}

var_dump($result->getUser());
/* */

/* DELETE *
$result = $userService->deleteUser($user);

echo "**After delete:\n";
if(!$result->isSuccess()){

    echo "ERROR: ";
    var_dump($result->getMessages());
}

var_dump($result->getUser());
/* */

/* */


/* AUTH ***********************************/

/* AUTH CHECK *
$authResult = $userService->validateCredentials($user);

echo "GenAuth Result: ".var_export($authResult->isValid(), true)."\n";
var_dump($authResult);
/* */

/*  LOG IN */
$authResult = $userService->authenticate($user);

echo "Sess Auth Result: ".var_export($authResult->isValid(), true)."\n";
var_dump($authResult);
/* */

/* GET SESSION USER *
echo "Session user: \n";
var_dump($userService->getIdentity());
/* */

/*  LOG OUT *
$userService->clearIdentity();

echo "Session user after log out: \n";
var_dump($userService->getIdentity());

/* */

/* ACL ************************************/
var_dump($bjyAuthService->getAcl()->getResources());
/* */

?>

</pre>