<?php
use Zend\Permissions\Acl\Acl;
use Zend\Permissions\Acl\Role\GenericRole as Role;
?>
<pre>
<?php
/* ACL STUFF
$x = $this->isAllowed('pants', 'wear');

$u = $this->zfcUserIdentity();

var_dump($u);

$acl = new Acl();
*/
//$userService = new RcmUser\Service\RcmUserService();
//var_dump($userService->getUserInputFilter()); die;

$user = $userService->buildNewUser();
var_dump($user);

$user->setId(null);
$user->setUsername('test999');
$user->setPassword(null);

echo "Before action:\n";
var_dump($user);
$result = $userService->createUser($user);

if(!$result->isSuccess()){

    echo "ERROR: \n";
    var_dump($result->getMessages());
    die;
}

var_dump($result->getUser());

/*
//$user = $userService->createUser($user);
$user = $userService->deleteUser($user);

echo "After action:\n";
if($user instanceof \Exception){

    echo "ERROR: " . $user->getMessage();
    die;
}

var_dump($user);
*/

?>

</pre>